### ISSUE TITLE
Torches don't ignite on client (but are lit on the server)

### ISSUE THREAD

**Issue by yaroslav4167** [codetaylor/pyrotech-1.12#333]
### Issue Description

I update pyrotech on my server to version 1.12.2-1.5.2 (earlier I had version 1.12.2-1.4.22). And torch_fiber / torch_stone stopped lighting up.

[Video reproduce](https://www.youtube.com/watch?v=fgO_ZlCZ-OY)

In singleplayer torches work fine.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2847
* CraftTweaker: 1.12-4.1.20.586
* Dropt: 1.12.2-1.18.0
* Pyrotech: 1.12.2-1.5.2
* Athenaeum: 1.12.2-1.19.2
* SpongeForge: 7.3.1-RC4093

**Comment by codetaylor** [comment]
Thanks for the report!

All blockstate changes are encoded to meta values when transmitted to the client. Since I forgot to override the methods for blockstate encoding in the torch block, the server was always sending the default state of `UNLIT` regardless of the actual state on the server.

This is fixed in `1.12.2-1.5.3`

**Comment by yaroslav4167** [comment]
I tested this commit. Torches lighting fine. but all torches are installed vertically only.
![J30lDVy8Il](https://user-images.githubusercontent.com/18057310/99944590-cf796980-2d7b-11eb-8059-89f3d9324594.gif)

**Comment by codetaylor** [comment]
That is a separate, but likely related issue.
