### ISSUE TITLE
Endless fuel

### ISSUE THREAD

**Issue by origin-s** [codetaylor/pyrotech-1.12#356]
If I use wooden bucket as fuel, it will never run out or disappear in furnace. It can keep burning for ever! And I tried to change it's burning time through crafttweaker, but it didn't work. Look forward to solving this problem soon.

* Minecraft:1.12.2
* Forge:14.23.5.2854
* CraftTweaker:1.12-4.1.20.574
* Dropt:1.12.2-1.18.0
* Pyrotech:1.12.2-1.5.11
* Athenaeum:1.12.2-1.13.2

**Comment by codetaylor** [comment]
This is due to the way that furnaces and buckets are coded.

When the furnace uses up a stack of fuel, it checks to see if the item has a container, which buckets do. The container is then returned and placed back in the fuel slot. This is coded to allow things like using a bucket of lava as fuel. If the bucket has lava, it returns a burn time and when it expires, the bucket is destroyed, then replaced with the container item - an empty bucket.

If the bucket itself is burnable, it breaks down. The wooden bucket is burned, destroyed, then the container item - the wooden bucket - is placed back in the fuel slot and it just never ends.

**Comment by codetaylor** [comment]
The only solution that I can see right now is to stop allowing the wooden bucket to be used as fuel.

**Comment by origin-s** [comment]
> The only solution that I can see right now is to stop allowing the wooden bucket to be used as fuel.

Well, thanks for your answer.
